uses: actions/setup-node@v4
        with:
          node-version: '23'    # 根据项目使用的 Node 版本调整
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload to OSS
        uses: aliyun/oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.OSS_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          bucket: guangda-cui      # 你的香港 Bucket 名称  
          endpoint: oss-cn-hongkong.aliyuncs.com
          folder: dist                # 本地构建输出目录
          # 如果你需要上传到 Bucket 的某个子目录，可以用 targetFolder 参数
          # targetFolder: myapp
